package net.sfedu.ars_maleficarum.entity.animations;
import net.minecraft.client.animation.AnimationChannel;
import net.minecraft.client.animation.AnimationDefinition;
import net.minecraft.client.animation.Keyframe;
import net.minecraft.client.animation.KeyframeAnimations;
public class ModAnimationDefenitions {

    public static final AnimationDefinition MANDRAKE_RUN = AnimationDefinition.Builder.withLength(1f)
            .addAnimation("nogalev",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("nogalev",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("nogalev",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_0",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.1f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, -0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_0",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2f, 7.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(1.89f, -11f, 2.52f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-2.53f, 9.99f, -3.05f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-1.31f, -3.95f, 7.01f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_0",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_1",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0.1f, 0f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_1",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-2f, 8f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(8.29f, -8.71f, -5.5f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-4.75f, 7.17f, 2.01f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-2.1f, -1.89f, 3.07f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_1",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_2",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -0.1f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_2",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-8.06f, 6.93f, -0.98f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.02f, -4.98f, -0.44f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-9.24f, 8.57f, -3.41f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-7.03f, -4.96f, 0.61f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_2",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_3",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, -0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, -0.2f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_3",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-7.76f, -1.53f, 3.79f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.01f, 2.99f, 0.26f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-5.83f, -7.92f, -1.97f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(8.96f, 0.92f, 0.88f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_3",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_4",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -0.1f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_4",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-7.4f, -12.32f, -3.81f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(7f, 5.46f, 6.5f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-11.05f, -7.49f, -2.98f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-3.28f, -8f, 2.02f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_4",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_5",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_5",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-11.13f, 8.83f, -1.73f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.53f, -11.24f, 1.88f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-9f, 5.99f, -0.49f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-0.49f, -6.98f, 4.03f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_5",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_6",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(-0.1f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_6",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-7.01f, -2.98f, 0.37f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(4.21f, 17.95f, 1.3f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-7.13f, -11.16f, -0.63f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(5.59f, 9.19f, -3.88f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_6",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_7",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(-0.1f, -0.1f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_7",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-9.01f, -5.46f, -5.19f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(14.59f, 12.42f, 8.19f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-10.09f, -11.22f, -2.02f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(7.33f, 3.35f, 5.46f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_7",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_8",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0.1f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_8",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-10.67f, 12.46f, -3.03f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(5.83f, -11.31f, 1.47f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-7.48f, 11.91f, -7.15f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(6f, 0f, 3f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_8",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_9",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(-0.1f, 0f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0.1f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0.1f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_9",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-9.6f, 23.44f, 2.58f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(19.63f, -5.41f, -5.82f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-5.94f, 11.95f, 5.11f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-2f, -4f, 4f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_9",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_10",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.2f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(-0.1f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0.1f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_10",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-9.13f, -14.22f, 5.53f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(14.01f, 14.07f, 4.02f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-18.22f, -8.89f, -4.58f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 0f, -9f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_10",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_11",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, -0.1f, -0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0.1f, 0.1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_11",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-15.87f, -29.75f, -3.61f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(29.27f, 30.47f, 30.6f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-13.24f, -28.95f, 0.51f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-0.79f, 8.97f, -5.06f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva_11",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("nogaprav",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("nogaprav",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-35f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("nogaprav",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tusha",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tusha",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(0f, 5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(0f, -7.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(0f, 7.5f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("tusha",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.scaleVec(1.02f, 1.03f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.25f, KeyframeAnimations.scaleVec(1f, 1.01f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.scaleVec(1.02f, 1.03f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.scaleVec(1.02f, 1.03f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.7083434f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.scaleVec(1.02f, 1.03f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.125f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.375f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.5834334f, KeyframeAnimations.degreeVec(20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.8343334f, KeyframeAnimations.degreeVec(-20f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(1f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR))).build();
    public static final AnimationDefinition MANDRAKE_IDLE = AnimationDefinition.Builder.withLength(3f)
            .addAnimation("listva",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-3f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.25f, KeyframeAnimations.degreeVec(4f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("listva",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.25f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukaprav",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.POSITION,
		new Keyframe(0f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.posVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.ROTATION,
		new Keyframe(0f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(0.75f, KeyframeAnimations.degreeVec(10f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(2.25f, KeyframeAnimations.degreeVec(-10f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.degreeVec(0f, 0f, 0f),
    AnimationChannel.Interpolations.LINEAR)))
            .addAnimation("rukalev",
                                  new AnimationChannel(AnimationChannel.Targets.SCALE,
		new Keyframe(0f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR),
            new Keyframe(3f, KeyframeAnimations.scaleVec(1f, 1f, 1f),
    AnimationChannel.Interpolations.LINEAR))).build();
}
